<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.skillforge</groupId>
    <artifactId>skillforge-backend</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>SkillForge Backend</name>
    <description>Parent Maven Project for SkillForge Microservices</description>

    <!-- ========================================================= -->
    <!-- MODULES -->
    <!-- ========================================================= -->

    <modules>
        <module>common-lib</module>
        <module>config-server</module>
        <module>discovery-server</module>
        <module>api-gateway</module>
<!--        <module>auth-service</module>-->
<!--        <module>user-service</module>-->
<!--        <module>course-service</module>-->
<!--        <module>assessment-service</module>-->
<!--        <module>notification-service</module>-->
<!--        <module>recommendation-service</module>-->
    </modules>

    <!-- ========================================================= -->
    <!-- PROPERTIES -->
    <!-- ========================================================= -->

    <properties>

        <!-- Java -->
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Spring -->
        <spring.boot.version>3.5.3</spring.boot.version>
        <spring.cloud.version>2025.0.0</spring.cloud.version>

        <!-- Libraries -->
        <lombok.version>1.18.38</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>

        <!-- Plugins -->
        <maven.compiler.plugin.version>3.14.0</maven.compiler.plugin.version>
        <spring.boot.maven.plugin.version>3.5.3</spring.boot.maven.plugin.version>

    </properties>

    <!-- ========================================================= -->
    <!-- DEPENDENCY MANAGEMENT -->
    <!-- ========================================================= -->

    <dependencyManagement>

        <dependencies>

            <!-- Spring Boot BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Spring Cloud BOM -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>

    </dependencyManagement>

    <!-- ========================================================= -->
    <!-- BUILD -->
    <!-- ========================================================= -->

    <build>

        <pluginManagement>

            <plugins>

                <!-- Java Compiler -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>

                    <configuration>

                        <source>${java.version}</source>
                        <target>${java.version}</target>

                        <annotationProcessorPaths>

                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>

                            <path>
                                <groupId>org.mapstruct</groupId>
                                <artifactId>mapstruct-processor</artifactId>
                                <version>${mapstruct.version}</version>
                            </path>

                        </annotationProcessorPaths>

                    </configuration>

                </plugin>

                <!-- Spring Boot -->
                <plugin>

                    <groupId>org.springframework.boot</groupId>

                    <artifactId>spring-boot-maven-plugin</artifactId>

                    <version>${spring.boot.maven.plugin.version}</version>

                </plugin>

            </plugins>

        </pluginManagement>

    </build>

</project>
